# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: |
        touch .env
        echo "${{ secrets.PROD_ENV_FILE }}" > .env
    #- run: pm2 restart BackendAPI
    - name: Run Tests
      run: npm test
    - name: Run Test Coverage
      run: npm run test:coverage
    - name: Run Vulnerability Scan
      run: npm audit --production --audit-level=high
    - run: |
        # Check if BackendAPI is running
        if pm2 list | grep -q 'BackendAPI'; then
          echo "BackendAPI is running, restarting..."
          pm2 start server.js --name=BackendAPI
        else
          echo "BackendAPI is not running, starting..."
          pm2 start BackendAPI
        fi